import { useState } from 'react';
import { ArrowUp, Bot, Check, Copy, Lightbulb, MessageCircle, Sparkles, UserRound } from 'lucide-react';
import { useAskCopilot } from '@workspace/api-client-react';
import { Avatar, Button, Card, PageHeader } from '@/components/devflow-ui';

type Message = { role: 'user' | 'assistant'; text: string; sources?: string[]; actions?: string[] };

const prompts = ['What should the team focus on today?', 'Which deadlines need attention?', 'Give me a concise project health readout'];

export default function AssistantPage() {
  const copilot = useAskCopilot();
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const ask = (message: string) => {
    const trimmed = message.trim();
    if (!trimmed || copilot.isPending) return;
    setInput('');
    setMessages((current) => [...current, { role: 'user', text: trimmed }]);
    copilot.mutate({ data: { message: trimmed } }, { onSuccess: (response) => setMessages((current) => [...current, { role: 'assistant', text: response.answer, sources: response.sources, actions: response.actions }]) });
  };
  return <div className="reveal">
    <PageHeader eyebrow="Workspace / Copilot" title="DevFlow Copilot" description="A grounded thinking partner for the work already in your workspace." action={<div className="flex items-center gap-2 rounded-lg border border-primary/25 bg-[#edf5d7] px-3 py-2 text-[10px] font-medium text-[#536d18]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-primary" /> Grounded in workspace data</div>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_320px]">
      <Card className="flex min-h-[600px] flex-col overflow-hidden">
        <div className="flex items-center gap-3 border-b border-border bg-secondary px-5 py-4 text-secondary-foreground"><div className="grid h-8 w-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Bot size={16} /></div><div><div className="text-sm font-semibold">Copilot</div><div className="mt-0.5 font-mono text-[9px] uppercase tracking-wider text-secondary-foreground/55">Workspace intelligence</div></div><div className="ml-auto flex items-center gap-1.5 font-mono text-[9px] text-secondary-foreground/55"><span className="h-1.5 w-1.5 rounded-full bg-primary" /> Online</div></div>
        <div className="scrollbar-thin flex-1 space-y-5 overflow-y-auto p-5 md:p-7">{messages.length === 0 ? <Welcome onAsk={ask} /> : messages.map((message, index) => <div key={`${message.role}-${index}`} className={`flex gap-3 reveal ${message.role === 'user' ? 'flex-row-reverse' : ''}`}><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${message.role === 'user' ? 'bg-[#d7e6ff] text-[#314b79]' : 'bg-[#edf5d7] text-[#637d22]'}`}>{message.role === 'user' ? <UserRound size={15} /> : <Sparkles size={15} />}</div><div className={`max-w-[82%] ${message.role === 'user' ? 'items-end text-right' : ''}`}><div className={`rounded-2xl px-4 py-3 text-sm leading-relaxed ${message.role === 'user' ? 'rounded-tr-sm bg-secondary text-secondary-foreground' : 'rounded-tl-sm bg-muted text-foreground'}`}>{message.text}</div>{message.sources && message.sources.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{message.sources.map((source) => <span key={source} className="rounded-md border border-border bg-card px-2 py-1 font-mono text-[9px] text-muted-foreground">{source}</span>)}</div>}{message.actions && message.actions.length > 0 && <div className="mt-3 space-y-1.5">{message.actions.map((action) => <div key={action} className="flex items-center gap-2 text-[10px] text-[#637d22]"><Check size={12} />{action}</div>)}</div>}<div className="mt-2 flex items-center gap-2 text-[9px] text-muted-foreground/60">{message.role === 'assistant' && <><button data-testid={`button-copy-response-${index}`} onClick={() => navigator.clipboard?.writeText(message.text)} className="inline-flex items-center gap-1 hover:text-foreground"><Copy size={10} /> Copy</button><span>·</span></>}<span>{message.role === 'user' ? 'You' : 'Copilot'}</span></div></div></div>)}{copilot.isPending && <div className="flex gap-3 reveal"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#edf5d7] text-[#637d22]"><Sparkles size={15} /></div><div className="rounded-2xl rounded-tl-sm bg-muted px-5 py-4"><div className="flex gap-1"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-muted-foreground" /><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-muted-foreground [animation-delay:150ms]" /><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-muted-foreground [animation-delay:300ms]" /></div></div></div>}{copilot.isError && <div className="ml-11 rounded-lg border border-destructive/20 bg-destructive/5 px-3 py-2 text-xs text-destructive">Copilot could not answer just now. Try asking again.</div>}</div>
        <div className="border-t border-border p-4"><div className="rounded-xl border border-input bg-background p-2 transition-colors focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/10"><textarea data-testid="input-copilot-message" value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); ask(input); } }} rows={2} placeholder="Ask about your workspace..." className="w-full resize-none bg-transparent px-2 py-1 text-sm outline-none placeholder:text-muted-foreground/60" /><div className="flex items-center justify-between px-2 pt-1"><span className="font-mono text-[9px] text-muted-foreground/60">Enter to send · Shift + Enter for a new line</span><button data-testid="button-send-copilot" onClick={() => ask(input)} disabled={!input.trim() || copilot.isPending} className="grid h-8 w-8 place-items-center rounded-lg bg-primary text-primary-foreground transition-all hover:brightness-105 disabled:opacity-40" aria-label="Send message"><ArrowUp size={15} /></button></div></div></div>
      </Card>
      <div className="space-y-5"><Card className="p-5"><div className="mb-4 flex items-center gap-2"><Lightbulb size={15} className="text-primary" /><h2 className="text-sm font-semibold">Try asking</h2></div><div className="space-y-2">{prompts.map((prompt) => <button data-testid={`button-prompt-${prompt.slice(0, 8).replaceAll(' ', '-').toLowerCase()}`} key={prompt} onClick={() => ask(prompt)} className="flex w-full items-start gap-2 rounded-lg border border-border p-3 text-left text-[11px] leading-relaxed text-muted-foreground transition-colors hover:border-primary/40 hover:bg-[#edf5d7]/40 hover:text-foreground"><MessageCircle size={13} className="mt-0.5 shrink-0 text-primary" />{prompt}</button>)}</div></Card><Card className="bg-[#edf5d7]/60 p-5"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#637d22]">Built for context</div><p className="mt-3 text-xs leading-relaxed text-[#52652b]">Copilot can connect project health, task flow, deadlines, and engineering activity so you can spend less time assembling the picture.</p><div className="mt-5 flex -space-x-2"><Avatar initials="MC" /><Avatar initials="JR" /><Avatar initials="AP" /><div className="grid h-6 w-6 place-items-center rounded-full border-2 border-[#edf5d7] bg-secondary font-mono text-[8px] text-secondary-foreground">+4</div></div></Card></div>
    </div>
  </div>;
}

function Welcome({ onAsk }: { onAsk: (prompt: string) => void }) {
  return <div className="flex h-full min-h-[460px] flex-col items-center justify-center text-center"><div className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-[#edf5d7] text-[#637d22] shadow-[0_0_0_8px_hsl(var(--primary)/.08)]"><Sparkles size={23} /></div><h2 className="text-xl font-semibold tracking-[-.03em]">What should we look at?</h2><p className="mt-2 max-w-sm text-xs leading-relaxed text-muted-foreground">Ask for a readout, a recommendation, or a sharper view of the work in motion.</p><div className="mt-7 flex flex-wrap justify-center gap-2">{prompts.map((prompt) => <button data-testid={`button-welcome-prompt-${prompt.slice(0, 6).replaceAll(' ', '-').toLowerCase()}`} key={prompt} onClick={() => onAsk(prompt)} className="rounded-full border border-border bg-card px-3 py-2 text-[10px] font-medium text-muted-foreground transition-colors hover:border-primary/40 hover:bg-[#edf5d7]/60 hover:text-foreground">{prompt}</button>)}</div></div>;
}