import { ArrowUpRight, CalendarClock, CheckCircle2, CircleDot, GitCommitHorizontal, Lightbulb, MoreHorizontal, Timer, TrendingUp, Users } from 'lucide-react';
import { getGetDashboardQueryKey, useGetDashboard } from '@workspace/api-client-react';
import { Link } from 'wouter';
import { Avatar, Card, ErrorState, LoadingState, PageHeader, SectionLabel, StatusPill } from '@/components/devflow-ui';

function Metric({ label, value, note, icon: Icon, tone = 'lime' }: { label: string; value: string | number; note: string; icon: typeof TrendingUp; tone?: 'lime' | 'blue' | 'coral' }) {
  const colors = { lime: 'bg-[#edf5d7] text-[#637d22]', blue: 'bg-[#dcecf0] text-[#276b79]', coral: 'bg-[#fbe4dc] text-[#9d4c37]' };
  return <Card className="p-5 transition-transform hover:-translate-y-0.5"><div className="flex items-start justify-between"><div className={`grid h-8 w-8 place-items-center rounded-lg ${colors[tone]}`}><Icon size={16} /></div><span className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">30d</span></div><div className="mt-5 text-[27px] font-semibold tracking-[-.05em]">{value}</div><div className="mt-1 text-xs font-medium text-muted-foreground">{label}</div><div className="mt-3 flex items-center gap-1.5 text-[10px] text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-primary" />{note}</div></Card>;
}

export default function DashboardPage() {
  const dashboard = useGetDashboard({ query: { queryKey: getGetDashboardQueryKey() } });
  if (dashboard.isLoading) return <><PageHeader eyebrow="Workspace pulse" title="Good morning, Maya." description="Here’s the signal across Northstar Labs." /><LoadingState rows={5} /></>;
  if (dashboard.isError || !dashboard.data) return <ErrorState onRetry={() => dashboard.refetch()} />;
  const data = dashboard.data;
  const maxProductivity = Math.max(...(data.productivity ?? []).map((point) => point.value), 1);
  const maxCompletion = Math.max(...(data.taskCompletion ?? []).map((point) => Math.max(point.completed, point.created)), 1);
  return <div className="reveal">
    <PageHeader eyebrow="Monday, 24 June 2024 · Workspace pulse" title="Good morning, Maya." description="Here’s the signal across Northstar Labs — focused work, visible progress, fewer loose ends." action={<Link data-testid="link-open-copilot" href="/assistant" className="inline-flex items-center gap-2 rounded-lg bg-secondary px-4 py-2.5 text-xs font-semibold text-secondary-foreground shadow-sm transition-transform hover:-translate-y-0.5"><Lightbulb size={15} className="text-primary" /> Ask Copilot <ArrowUpRight size={14} /></Link>} />
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4 md:gap-4">
      <Metric label="Active projects" value={data.activeProjects} note={`${data.totalProjects} total in workspace`} icon={CircleDot} />
      <Metric label="Tasks completed" value={data.completedTasks} note="Up 12% from last month" icon={CheckCircle2} tone="blue" />
      <Metric label="Tasks in motion" value={data.pendingTasks} note="4 need attention this week" icon={Timer} tone="coral" />
      <Metric label="Team members" value={data.teamMembers} note="3 active today" icon={Users} tone="lime" />
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <Card className="p-5 md:p-6"><SectionLabel action={<span className="font-mono text-[10px] text-muted-foreground">May 27 — Jun 24</span>}>Productivity rhythm</SectionLabel><div className="mt-6 flex h-[178px] items-end gap-2 md:gap-4">{(data.productivity ?? []).map((point) => <div key={point.label} data-testid={`chart-productivity-${point.label}`} className="group flex min-w-0 flex-1 flex-col items-center gap-2"><div className="relative flex h-[145px] w-full items-end justify-center"><div className="absolute bottom-0 h-px w-full bg-border" /><div className="w-full max-w-[34px] rounded-t-md bg-[#b9d85f] transition-all duration-500 group-hover:bg-primary" style={{ height: `${Math.max((point.value / maxProductivity) * 100, 5)}%` }}><span className="absolute -top-5 left-1/2 hidden -translate-x-1/2 rounded bg-secondary px-1.5 py-0.5 font-mono text-[9px] text-secondary-foreground group-hover:block">{point.value}</span></div></div><span className="truncate font-mono text-[9px] text-muted-foreground">{point.label}</span></div>)}</div><div className="mt-6 flex items-center justify-between border-t border-border pt-4"><div><div className="text-xs font-semibold">Momentum is holding</div><div className="mt-1 text-[10px] text-muted-foreground">Most productive window: Tuesday morning</div></div><div className="flex items-center gap-1.5 font-mono text-[10px] text-[#637d22]"><TrendingUp size={13} /> 18.4%</div></div></Card>
      <Card className="p-5 md:p-6"><SectionLabel>Task completion</SectionLabel><div className="mt-8 flex items-center justify-center"><div className="relative grid h-40 w-40 place-items-center rounded-full" style={{ background: `conic-gradient(hsl(var(--primary)) 0 68%, hsl(var(--muted)) 68% 100%)` }}><div className="grid h-28 w-28 place-items-center rounded-full bg-card"><div className="text-center"><div className="text-2xl font-semibold tracking-[-.06em]">68%</div><div className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">complete</div></div></div></div></div><div className="mt-6 space-y-2.5">{(data.taskCompletion ?? []).slice(-3).map((point) => <div key={point.label} className="flex items-center justify-between text-[11px]"><span className="text-muted-foreground">{point.label}</span><div className="flex items-center gap-3 font-mono text-[10px]"><span className="text-foreground">{point.completed} done</span><span className="text-muted-foreground/60">/ {point.created} opened</span></div></div>)}</div></Card>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_1fr]">
      <Card className="p-5 md:p-6"><SectionLabel action={<Link data-testid="link-view-projects" href="/projects" className="text-[10px] font-semibold text-primary hover:underline">All projects →</Link>}>Upcoming deadlines</SectionLabel><div className="divide-y divide-border">{data.deadlines?.length ? data.deadlines.slice(0, 4).map((deadline) => <div data-testid={`deadline-${deadline.id}`} key={deadline.id} className="flex items-center gap-3 py-3.5"><div className={`grid h-8 w-8 place-items-center rounded-lg ${deadline.daysLeft <= 3 ? 'bg-[#fbe4dc] text-[#9d4c37]' : 'bg-muted text-muted-foreground'}`}><CalendarClock size={15} /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{deadline.title}</div><div className="mt-1 text-[10px] text-muted-foreground">{deadline.project} · {deadline.dueDate}</div></div><div className="text-right"><div className={`font-mono text-[10px] font-medium ${deadline.daysLeft <= 3 ? 'text-[#b5563d]' : 'text-muted-foreground'}`}>{deadline.daysLeft === 0 ? 'Today' : `${deadline.daysLeft}d left`}</div><div className="mt-1"><StatusPill value={deadline.daysLeft <= 3 ? 'attention' : 'on track'} /></div></div></div>) : <div className="py-8"><p className="text-center text-xs text-muted-foreground">No deadlines on the horizon.</p></div>}</div></Card>
      <Card className="p-5 md:p-6"><SectionLabel action={<Link data-testid="link-view-activity" href="/activity" className="text-[10px] font-semibold text-primary hover:underline">View activity →</Link>}>Recent activity</SectionLabel><div className="divide-y divide-border">{data.recentActivity?.slice(0, 4).map((item) => <div data-testid={`activity-dashboard-${item.id}`} key={item.id} className="flex gap-3 py-3.5"><Avatar initials={item.userInitials} /><div className="min-w-0 flex-1"><div className="text-xs"><span className="font-semibold">{item.user}</span> <span className="text-muted-foreground">{item.title}</span></div><div className="mt-1 truncate text-[10px] text-muted-foreground">{item.description}</div></div><span className="shrink-0 font-mono text-[9px] text-muted-foreground/65">{item.timestamp}</span></div>)}</div></Card>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[.92fr_1.08fr]">
      <Card className="overflow-hidden bg-secondary text-secondary-foreground"><div className="flex items-center justify-between border-b border-secondary-foreground/10 px-5 py-4"><SectionLabel><span className="text-secondary-foreground/60">Copilot brief</span></SectionLabel><BotGlyph /></div><div className="p-5"><div className="mb-4 font-mono text-[9px] uppercase tracking-[.18em] text-primary">One thing worth knowing</div>{data.insights?.[0] ? <><h3 className="text-[20px] font-semibold leading-tight tracking-[-.03em]">{data.insights[0].title}</h3><p className="mt-3 text-xs leading-relaxed text-secondary-foreground/65">{data.insights[0].body}</p></> : <p className="text-sm text-secondary-foreground/60">Your workspace is looking healthy.</p>}<Link data-testid="link-read-insights" href="/assistant" className="mt-6 inline-flex items-center gap-2 text-[11px] font-semibold text-primary hover:underline">Open full brief <ArrowUpRight size={13} /></Link></div></Card>
      <Card className="p-5 md:p-6"><SectionLabel action={<span className="font-mono text-[10px] text-muted-foreground">last 7 days</span>}>Engineering activity</SectionLabel><div className="divide-y divide-border">{data.githubActivity?.slice(0, 4).map((item) => <div data-testid={`github-activity-${item.id}`} key={item.id} className="flex items-center gap-3 py-3.5"><div className="grid h-8 w-8 place-items-center rounded-lg bg-muted text-muted-foreground"><GitCommitHorizontal size={15} /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{item.title}</div><div className="mt-1 flex gap-2 text-[10px] text-muted-foreground"><span>{item.repository}</span><span className="text-border">·</span><span>{item.author}</span></div></div><span className="font-mono text-[9px] text-muted-foreground/65">{item.timestamp}</span><MoreHorizontal size={14} className="text-muted-foreground/50" /></div>)}</div></Card>
    </div>
  </div>;
}

function BotGlyph() {
  return <div className="grid h-7 w-7 place-items-center rounded-lg bg-primary text-primary-foreground"><BotIcon /></div>;
}
function BotIcon() { return <span className="font-mono text-[11px] font-bold">AI</span>; }