import { useState } from 'react';
import { Check, Github, Globe2, LockKeyhole, Save, SlidersHorizontal, Users } from 'lucide-react';
import { Button, Card, Field, Input, PageHeader, Select } from '@/components/devflow-ui';

export default function SettingsPage() {
  const [saved, setSaved] = useState(false);
  const [name, setName] = useState('Northstar Labs');
  const [description, setDescription] = useState('A small product engineering team building useful things for thoughtful teams.');
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2400); };
  return <div className="reveal">
    <PageHeader eyebrow="Workspace / Settings" title="Settings" description="Shape how Northstar Labs looks, works, and stays connected." />
    <div className="grid gap-5 lg:grid-cols-[220px_1fr]">
      <nav className="flex gap-1 overflow-x-auto lg:block lg:space-y-1"><a data-testid="link-settings-general" href="#general" className="flex shrink-0 items-center gap-2 rounded-lg bg-secondary px-3 py-2.5 text-xs font-medium text-secondary-foreground"><SlidersHorizontal size={14} /> General</a><a data-testid="link-settings-members" href="#members" className="flex shrink-0 items-center gap-2 rounded-lg px-3 py-2.5 text-xs font-medium text-muted-foreground hover:bg-muted"><Users size={14} /> Members</a><a data-testid="link-settings-integrations" href="#integrations" className="flex shrink-0 items-center gap-2 rounded-lg px-3 py-2.5 text-xs font-medium text-muted-foreground hover:bg-muted"><Github size={14} /> Integrations</a></nav>
      <div className="space-y-5">
        <Card id="general" className="p-5 md:p-6"><div className="flex items-start justify-between border-b border-border pb-5"><div><h2 className="text-sm font-semibold">Workspace identity</h2><p className="mt-1 text-xs text-muted-foreground">The basics your team sees across DevFlow.</p></div><div className="grid h-10 w-10 place-items-center rounded-xl bg-secondary font-mono text-xs text-primary">NL</div></div><div className="mt-5 space-y-4"><Field label="Workspace name"><Input data-testid="input-workspace-name" value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Description"><Input data-testid="input-workspace-description" value={description} onChange={(event) => setDescription(event.target.value)} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Timezone"><Select data-testid="select-workspace-timezone" defaultValue="pacific"><option value="pacific">Pacific Time (UTC−08:00)</option><option value="eastern">Eastern Time (UTC−05:00)</option><option value="london">London (UTC+00:00)</option></Select></Field><Field label="Week starts on"><Select data-testid="select-week-start" defaultValue="monday"><option value="monday">Monday</option><option value="sunday">Sunday</option></Select></Field></div></div><div className="mt-6 flex items-center justify-end gap-3 border-t border-border pt-5">{saved && <span className="flex items-center gap-1.5 text-[11px] text-[#637d22]"><Check size={13} /> Changes saved</span>}<Button onClick={save}><Save size={14} /> Save changes</Button></div></Card>
        <Card id="members" className="p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Member access</h2><p className="mt-1 text-xs text-muted-foreground">Manage who can see and shape this workspace.</p></div><Button variant="secondary" onClick={() => setSaved(true)}>Invite member</Button></div><div className="mt-5 divide-y divide-border"><Member initials="MC" name="Maya Chen" detail="You · Admin" /><Member initials="JR" name="Jonas Rivera" detail="Engineering · Member" /><Member initials="AP" name="Ari Patel" detail="Design · Member" /></div></Card>
        <Card id="integrations" className="p-5 md:p-6"><div className="mb-5"><h2 className="text-sm font-semibold">Connected tools</h2><p className="mt-1 text-xs text-muted-foreground">Where DevFlow picks up the engineering signal.</p></div><div className="flex items-center justify-between rounded-xl border border-border p-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-secondary text-primary"><Github size={17} /></div><div><div className="text-xs font-semibold">GitHub</div><div className="mt-1 flex items-center gap-1.5 text-[10px] text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-primary" /> Connected to northstar-labs</div></div></div><Button variant="ghost" onClick={() => setSaved(true)}>Manage</Button></div><div className="mt-3 flex items-center justify-between rounded-xl border border-border p-4 opacity-75"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-muted text-muted-foreground"><Globe2 size={17} /></div><div><div className="text-xs font-semibold">Linear sync</div><div className="mt-1 text-[10px] text-muted-foreground">Not connected</div></div></div><Button variant="secondary" onClick={() => setSaved(true)}>Connect</Button></div></Card>
        <div className="flex items-center gap-2 rounded-lg border border-border bg-muted/40 px-4 py-3 text-[10px] text-muted-foreground"><LockKeyhole size={13} /> Workspace settings are visible to admins only. Changes in this first slice are local to this session.</div>
      </div>
    </div>
  </div>;
}

function Member({ initials, name, detail }: { initials: string; name: string; detail: string }) {
  return <div className="flex items-center gap-3 py-3"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#d7e6ff] font-mono text-[9px] text-[#314b79]">{initials}</div><div className="flex-1"><div className="text-xs font-medium">{name}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{detail}</div></div><span className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">Active</span></div>;
}